language: minimal
sudo: required
services:
  - docker
before_script:
  - tag="${TRAVIS_TAG:-latest}"
  - image_name=${image_name:-${TRAVIS_REPO_SLUG%/*}}
  - docker_org="actions"
script:
  - docker build -t ${docker_org}/${image_name}:${tag} .
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  - provider: script
    script: docker push ${docker_org}/${image_name}:${tag}
    on:
      branch: master
  - provider: script
    script: docker push ${docker_org}/${image_name}:${tag}
    on:
      branch: master
      tags: true
env:
  - image_name=pip
  - image_name=pip3
